// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_file_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_file_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "../comm.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_file_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_file_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_file_2eproto;
namespace messageSystem {
class GetFileReq;
struct GetFileReqDefaultTypeInternal;
extern GetFileReqDefaultTypeInternal _GetFileReq_default_instance_;
class GetFileRsp;
struct GetFileRspDefaultTypeInternal;
extern GetFileRspDefaultTypeInternal _GetFileRsp_default_instance_;
class GetFileRsp_FileDataEntry_DoNotUse;
struct GetFileRsp_FileDataEntry_DoNotUseDefaultTypeInternal;
extern GetFileRsp_FileDataEntry_DoNotUseDefaultTypeInternal _GetFileRsp_FileDataEntry_DoNotUse_default_instance_;
class PutFileReq;
struct PutFileReqDefaultTypeInternal;
extern PutFileReqDefaultTypeInternal _PutFileReq_default_instance_;
class PutFileRsp;
struct PutFileRspDefaultTypeInternal;
extern PutFileRspDefaultTypeInternal _PutFileRsp_default_instance_;
}  // namespace messageSystem
PROTOBUF_NAMESPACE_OPEN
template<> ::messageSystem::GetFileReq* Arena::CreateMaybeMessage<::messageSystem::GetFileReq>(Arena*);
template<> ::messageSystem::GetFileRsp* Arena::CreateMaybeMessage<::messageSystem::GetFileRsp>(Arena*);
template<> ::messageSystem::GetFileRsp_FileDataEntry_DoNotUse* Arena::CreateMaybeMessage<::messageSystem::GetFileRsp_FileDataEntry_DoNotUse>(Arena*);
template<> ::messageSystem::PutFileReq* Arena::CreateMaybeMessage<::messageSystem::PutFileReq>(Arena*);
template<> ::messageSystem::PutFileRsp* Arena::CreateMaybeMessage<::messageSystem::PutFileRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace messageSystem {

// ===================================================================

class GetFileReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messageSystem.GetFileReq) */ {
 public:
  inline GetFileReq() : GetFileReq(nullptr) {}
  ~GetFileReq() override;
  explicit PROTOBUF_CONSTEXPR GetFileReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetFileReq(const GetFileReq& from);
  GetFileReq(GetFileReq&& from) noexcept
    : GetFileReq() {
    *this = ::std::move(from);
  }

  inline GetFileReq& operator=(const GetFileReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetFileReq& operator=(GetFileReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetFileReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetFileReq* internal_default_instance() {
    return reinterpret_cast<const GetFileReq*>(
               &_GetFileReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetFileReq& a, GetFileReq& b) {
    a.Swap(&b);
  }
  inline void Swap(GetFileReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetFileReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetFileReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetFileReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetFileReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetFileReq& from) {
    GetFileReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetFileReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messageSystem.GetFileReq";
  }
  protected:
  explicit GetFileReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileIdListFieldNumber = 4,
    kRequestIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kSessionIdFieldNumber = 3,
  };
  // repeated string file_id_list = 4;
  int file_id_list_size() const;
  private:
  int _internal_file_id_list_size() const;
  public:
  void clear_file_id_list();
  const std::string& file_id_list(int index) const;
  std::string* mutable_file_id_list(int index);
  void set_file_id_list(int index, const std::string& value);
  void set_file_id_list(int index, std::string&& value);
  void set_file_id_list(int index, const char* value);
  void set_file_id_list(int index, const char* value, size_t size);
  std::string* add_file_id_list();
  void add_file_id_list(const std::string& value);
  void add_file_id_list(std::string&& value);
  void add_file_id_list(const char* value);
  void add_file_id_list(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& file_id_list() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_file_id_list();
  private:
  const std::string& _internal_file_id_list(int index) const;
  std::string* _internal_add_file_id_list();
  public:

  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request_id();
  PROTOBUF_NODISCARD std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // optional string user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // optional string session_id = 3;
  bool has_session_id() const;
  private:
  bool _internal_has_session_id() const;
  public:
  void clear_session_id();
  const std::string& session_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // @@protoc_insertion_point(class_scope:messageSystem.GetFileReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> file_id_list_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// -------------------------------------------------------------------

class GetFileRsp_FileDataEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GetFileRsp_FileDataEntry_DoNotUse, 
    std::string, ::messageSystem::FileDownloadData,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<GetFileRsp_FileDataEntry_DoNotUse, 
    std::string, ::messageSystem::FileDownloadData,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  GetFileRsp_FileDataEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR GetFileRsp_FileDataEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit GetFileRsp_FileDataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const GetFileRsp_FileDataEntry_DoNotUse& other);
  static const GetFileRsp_FileDataEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const GetFileRsp_FileDataEntry_DoNotUse*>(&_GetFileRsp_FileDataEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "messageSystem.GetFileRsp.FileDataEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_file_2eproto;
};

// -------------------------------------------------------------------

class GetFileRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messageSystem.GetFileRsp) */ {
 public:
  inline GetFileRsp() : GetFileRsp(nullptr) {}
  ~GetFileRsp() override;
  explicit PROTOBUF_CONSTEXPR GetFileRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetFileRsp(const GetFileRsp& from);
  GetFileRsp(GetFileRsp&& from) noexcept
    : GetFileRsp() {
    *this = ::std::move(from);
  }

  inline GetFileRsp& operator=(const GetFileRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetFileRsp& operator=(GetFileRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetFileRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetFileRsp* internal_default_instance() {
    return reinterpret_cast<const GetFileRsp*>(
               &_GetFileRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetFileRsp& a, GetFileRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(GetFileRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetFileRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetFileRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetFileRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetFileRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetFileRsp& from) {
    GetFileRsp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetFileRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messageSystem.GetFileRsp";
  }
  protected:
  explicit GetFileRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kFileDataFieldNumber = 4,
    kRequestIdFieldNumber = 1,
    kErrmsgFieldNumber = 3,
    kSuccessFieldNumber = 2,
  };
  // map<string, .messageSystem.FileDownloadData> file_data = 4;
  int file_data_size() const;
  private:
  int _internal_file_data_size() const;
  public:
  void clear_file_data();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >&
      _internal_file_data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >*
      _internal_mutable_file_data();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >&
      file_data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >*
      mutable_file_data();

  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request_id();
  PROTOBUF_NODISCARD std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:messageSystem.GetFileRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        GetFileRsp_FileDataEntry_DoNotUse,
        std::string, ::messageSystem::FileDownloadData,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> file_data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// -------------------------------------------------------------------

class PutFileReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messageSystem.PutFileReq) */ {
 public:
  inline PutFileReq() : PutFileReq(nullptr) {}
  ~PutFileReq() override;
  explicit PROTOBUF_CONSTEXPR PutFileReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PutFileReq(const PutFileReq& from);
  PutFileReq(PutFileReq&& from) noexcept
    : PutFileReq() {
    *this = ::std::move(from);
  }

  inline PutFileReq& operator=(const PutFileReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline PutFileReq& operator=(PutFileReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PutFileReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const PutFileReq* internal_default_instance() {
    return reinterpret_cast<const PutFileReq*>(
               &_PutFileReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PutFileReq& a, PutFileReq& b) {
    a.Swap(&b);
  }
  inline void Swap(PutFileReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PutFileReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PutFileReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PutFileReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PutFileReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PutFileReq& from) {
    PutFileReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PutFileReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messageSystem.PutFileReq";
  }
  protected:
  explicit PutFileReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileDataFieldNumber = 4,
    kRequestIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kSessionIdFieldNumber = 3,
  };
  // repeated .messageSystem.FileUploadData file_data = 4;
  int file_data_size() const;
  private:
  int _internal_file_data_size() const;
  public:
  void clear_file_data();
  ::messageSystem::FileUploadData* mutable_file_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileUploadData >*
      mutable_file_data();
  private:
  const ::messageSystem::FileUploadData& _internal_file_data(int index) const;
  ::messageSystem::FileUploadData* _internal_add_file_data();
  public:
  const ::messageSystem::FileUploadData& file_data(int index) const;
  ::messageSystem::FileUploadData* add_file_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileUploadData >&
      file_data() const;

  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request_id();
  PROTOBUF_NODISCARD std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // optional string user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // optional string session_id = 3;
  bool has_session_id() const;
  private:
  bool _internal_has_session_id() const;
  public:
  void clear_session_id();
  const std::string& session_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // @@protoc_insertion_point(class_scope:messageSystem.PutFileReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileUploadData > file_data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// -------------------------------------------------------------------

class PutFileRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messageSystem.PutFileRsp) */ {
 public:
  inline PutFileRsp() : PutFileRsp(nullptr) {}
  ~PutFileRsp() override;
  explicit PROTOBUF_CONSTEXPR PutFileRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PutFileRsp(const PutFileRsp& from);
  PutFileRsp(PutFileRsp&& from) noexcept
    : PutFileRsp() {
    *this = ::std::move(from);
  }

  inline PutFileRsp& operator=(const PutFileRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline PutFileRsp& operator=(PutFileRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PutFileRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const PutFileRsp* internal_default_instance() {
    return reinterpret_cast<const PutFileRsp*>(
               &_PutFileRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PutFileRsp& a, PutFileRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(PutFileRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PutFileRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PutFileRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PutFileRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PutFileRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PutFileRsp& from) {
    PutFileRsp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PutFileRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messageSystem.PutFileRsp";
  }
  protected:
  explicit PutFileRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileInfoFieldNumber = 4,
    kRequestIdFieldNumber = 1,
    kErrmsgFieldNumber = 3,
    kSuccessFieldNumber = 2,
  };
  // repeated .messageSystem.FileMessageInfo file_info = 4;
  int file_info_size() const;
  private:
  int _internal_file_info_size() const;
  public:
  void clear_file_info();
  ::messageSystem::FileMessageInfo* mutable_file_info(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileMessageInfo >*
      mutable_file_info();
  private:
  const ::messageSystem::FileMessageInfo& _internal_file_info(int index) const;
  ::messageSystem::FileMessageInfo* _internal_add_file_info();
  public:
  const ::messageSystem::FileMessageInfo& file_info(int index) const;
  ::messageSystem::FileMessageInfo* add_file_info();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileMessageInfo >&
      file_info() const;

  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request_id();
  PROTOBUF_NODISCARD std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:messageSystem.PutFileRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileMessageInfo > file_info_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// ===================================================================

class FileService_Stub;

class FileService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline FileService() {};
 public:
  virtual ~FileService();

  typedef FileService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void GetSingleFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::GetFileReq* request,
                       ::messageSystem::GetFileRsp* response,
                       ::google::protobuf::Closure* done);
  virtual void GetMultiFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::GetFileReq* request,
                       ::messageSystem::GetFileRsp* response,
                       ::google::protobuf::Closure* done);
  virtual void PutSingleFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::PutFileReq* request,
                       ::messageSystem::PutFileRsp* response,
                       ::google::protobuf::Closure* done);
  virtual void PutMultiFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::PutFileReq* request,
                       ::messageSystem::PutFileRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(FileService);
};

class FileService_Stub : public FileService {
 public:
  FileService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  FileService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~FileService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements FileService ------------------------------------------

  void GetSingleFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::GetFileReq* request,
                       ::messageSystem::GetFileRsp* response,
                       ::google::protobuf::Closure* done);
  void GetMultiFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::GetFileReq* request,
                       ::messageSystem::GetFileRsp* response,
                       ::google::protobuf::Closure* done);
  void PutSingleFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::PutFileReq* request,
                       ::messageSystem::PutFileRsp* response,
                       ::google::protobuf::Closure* done);
  void PutMultiFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::messageSystem::PutFileReq* request,
                       ::messageSystem::PutFileRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(FileService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetFileReq

// string request_id = 1;
inline void GetFileReq::clear_request_id() {
  _impl_.request_id_.ClearToEmpty();
}
inline const std::string& GetFileReq::request_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.GetFileReq.request_id)
  return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetFileReq::set_request_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.GetFileReq.request_id)
}
inline std::string* GetFileReq::mutable_request_id() {
  std::string* _s = _internal_mutable_request_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.GetFileReq.request_id)
  return _s;
}
inline const std::string& GetFileReq::_internal_request_id() const {
  return _impl_.request_id_.Get();
}
inline void GetFileReq::_internal_set_request_id(const std::string& value) {
  
  _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string* GetFileReq::_internal_mutable_request_id() {
  
  return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string* GetFileReq::release_request_id() {
  // @@protoc_insertion_point(field_release:messageSystem.GetFileReq.request_id)
  return _impl_.request_id_.Release();
}
inline void GetFileReq::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_id_.IsDefault()) {
    _impl_.request_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.GetFileReq.request_id)
}

// optional string user_id = 2;
inline bool GetFileReq::_internal_has_user_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GetFileReq::has_user_id() const {
  return _internal_has_user_id();
}
inline void GetFileReq::clear_user_id() {
  _impl_.user_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GetFileReq::user_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.GetFileReq.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetFileReq::set_user_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.user_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.GetFileReq.user_id)
}
inline std::string* GetFileReq::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.GetFileReq.user_id)
  return _s;
}
inline const std::string& GetFileReq::_internal_user_id() const {
  return _impl_.user_id_.Get();
}
inline void GetFileReq::_internal_set_user_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.user_id_.Set(value, GetArenaForAllocation());
}
inline std::string* GetFileReq::_internal_mutable_user_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.user_id_.Mutable(GetArenaForAllocation());
}
inline std::string* GetFileReq::release_user_id() {
  // @@protoc_insertion_point(field_release:messageSystem.GetFileReq.user_id)
  if (!_internal_has_user_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.user_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void GetFileReq::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.user_id_.SetAllocated(user_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.GetFileReq.user_id)
}

// optional string session_id = 3;
inline bool GetFileReq::_internal_has_session_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool GetFileReq::has_session_id() const {
  return _internal_has_session_id();
}
inline void GetFileReq::clear_session_id() {
  _impl_.session_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& GetFileReq::session_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.GetFileReq.session_id)
  return _internal_session_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetFileReq::set_session_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.session_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.GetFileReq.session_id)
}
inline std::string* GetFileReq::mutable_session_id() {
  std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.GetFileReq.session_id)
  return _s;
}
inline const std::string& GetFileReq::_internal_session_id() const {
  return _impl_.session_id_.Get();
}
inline void GetFileReq::_internal_set_session_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.session_id_.Set(value, GetArenaForAllocation());
}
inline std::string* GetFileReq::_internal_mutable_session_id() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.session_id_.Mutable(GetArenaForAllocation());
}
inline std::string* GetFileReq::release_session_id() {
  // @@protoc_insertion_point(field_release:messageSystem.GetFileReq.session_id)
  if (!_internal_has_session_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.session_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void GetFileReq::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.session_id_.SetAllocated(session_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.GetFileReq.session_id)
}

// repeated string file_id_list = 4;
inline int GetFileReq::_internal_file_id_list_size() const {
  return _impl_.file_id_list_.size();
}
inline int GetFileReq::file_id_list_size() const {
  return _internal_file_id_list_size();
}
inline void GetFileReq::clear_file_id_list() {
  _impl_.file_id_list_.Clear();
}
inline std::string* GetFileReq::add_file_id_list() {
  std::string* _s = _internal_add_file_id_list();
  // @@protoc_insertion_point(field_add_mutable:messageSystem.GetFileReq.file_id_list)
  return _s;
}
inline const std::string& GetFileReq::_internal_file_id_list(int index) const {
  return _impl_.file_id_list_.Get(index);
}
inline const std::string& GetFileReq::file_id_list(int index) const {
  // @@protoc_insertion_point(field_get:messageSystem.GetFileReq.file_id_list)
  return _internal_file_id_list(index);
}
inline std::string* GetFileReq::mutable_file_id_list(int index) {
  // @@protoc_insertion_point(field_mutable:messageSystem.GetFileReq.file_id_list)
  return _impl_.file_id_list_.Mutable(index);
}
inline void GetFileReq::set_file_id_list(int index, const std::string& value) {
  _impl_.file_id_list_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:messageSystem.GetFileReq.file_id_list)
}
inline void GetFileReq::set_file_id_list(int index, std::string&& value) {
  _impl_.file_id_list_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:messageSystem.GetFileReq.file_id_list)
}
inline void GetFileReq::set_file_id_list(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.file_id_list_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:messageSystem.GetFileReq.file_id_list)
}
inline void GetFileReq::set_file_id_list(int index, const char* value, size_t size) {
  _impl_.file_id_list_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:messageSystem.GetFileReq.file_id_list)
}
inline std::string* GetFileReq::_internal_add_file_id_list() {
  return _impl_.file_id_list_.Add();
}
inline void GetFileReq::add_file_id_list(const std::string& value) {
  _impl_.file_id_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:messageSystem.GetFileReq.file_id_list)
}
inline void GetFileReq::add_file_id_list(std::string&& value) {
  _impl_.file_id_list_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:messageSystem.GetFileReq.file_id_list)
}
inline void GetFileReq::add_file_id_list(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.file_id_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:messageSystem.GetFileReq.file_id_list)
}
inline void GetFileReq::add_file_id_list(const char* value, size_t size) {
  _impl_.file_id_list_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:messageSystem.GetFileReq.file_id_list)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetFileReq::file_id_list() const {
  // @@protoc_insertion_point(field_list:messageSystem.GetFileReq.file_id_list)
  return _impl_.file_id_list_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetFileReq::mutable_file_id_list() {
  // @@protoc_insertion_point(field_mutable_list:messageSystem.GetFileReq.file_id_list)
  return &_impl_.file_id_list_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GetFileRsp

// string request_id = 1;
inline void GetFileRsp::clear_request_id() {
  _impl_.request_id_.ClearToEmpty();
}
inline const std::string& GetFileRsp::request_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.GetFileRsp.request_id)
  return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetFileRsp::set_request_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.GetFileRsp.request_id)
}
inline std::string* GetFileRsp::mutable_request_id() {
  std::string* _s = _internal_mutable_request_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.GetFileRsp.request_id)
  return _s;
}
inline const std::string& GetFileRsp::_internal_request_id() const {
  return _impl_.request_id_.Get();
}
inline void GetFileRsp::_internal_set_request_id(const std::string& value) {
  
  _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string* GetFileRsp::_internal_mutable_request_id() {
  
  return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string* GetFileRsp::release_request_id() {
  // @@protoc_insertion_point(field_release:messageSystem.GetFileRsp.request_id)
  return _impl_.request_id_.Release();
}
inline void GetFileRsp::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_id_.IsDefault()) {
    _impl_.request_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.GetFileRsp.request_id)
}

// bool success = 2;
inline void GetFileRsp::clear_success() {
  _impl_.success_ = false;
}
inline bool GetFileRsp::_internal_success() const {
  return _impl_.success_;
}
inline bool GetFileRsp::success() const {
  // @@protoc_insertion_point(field_get:messageSystem.GetFileRsp.success)
  return _internal_success();
}
inline void GetFileRsp::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void GetFileRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:messageSystem.GetFileRsp.success)
}

// string errmsg = 3;
inline void GetFileRsp::clear_errmsg() {
  _impl_.errmsg_.ClearToEmpty();
}
inline const std::string& GetFileRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:messageSystem.GetFileRsp.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetFileRsp::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errmsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.GetFileRsp.errmsg)
}
inline std::string* GetFileRsp::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:messageSystem.GetFileRsp.errmsg)
  return _s;
}
inline const std::string& GetFileRsp::_internal_errmsg() const {
  return _impl_.errmsg_.Get();
}
inline void GetFileRsp::_internal_set_errmsg(const std::string& value) {
  
  _impl_.errmsg_.Set(value, GetArenaForAllocation());
}
inline std::string* GetFileRsp::_internal_mutable_errmsg() {
  
  return _impl_.errmsg_.Mutable(GetArenaForAllocation());
}
inline std::string* GetFileRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:messageSystem.GetFileRsp.errmsg)
  return _impl_.errmsg_.Release();
}
inline void GetFileRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  _impl_.errmsg_.SetAllocated(errmsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errmsg_.IsDefault()) {
    _impl_.errmsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.GetFileRsp.errmsg)
}

// map<string, .messageSystem.FileDownloadData> file_data = 4;
inline int GetFileRsp::_internal_file_data_size() const {
  return _impl_.file_data_.size();
}
inline int GetFileRsp::file_data_size() const {
  return _internal_file_data_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >&
GetFileRsp::_internal_file_data() const {
  return _impl_.file_data_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >&
GetFileRsp::file_data() const {
  // @@protoc_insertion_point(field_map:messageSystem.GetFileRsp.file_data)
  return _internal_file_data();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >*
GetFileRsp::_internal_mutable_file_data() {
  return _impl_.file_data_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::messageSystem::FileDownloadData >*
GetFileRsp::mutable_file_data() {
  // @@protoc_insertion_point(field_mutable_map:messageSystem.GetFileRsp.file_data)
  return _internal_mutable_file_data();
}

// -------------------------------------------------------------------

// PutFileReq

// string request_id = 1;
inline void PutFileReq::clear_request_id() {
  _impl_.request_id_.ClearToEmpty();
}
inline const std::string& PutFileReq::request_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileReq.request_id)
  return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PutFileReq::set_request_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.PutFileReq.request_id)
}
inline std::string* PutFileReq::mutable_request_id() {
  std::string* _s = _internal_mutable_request_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.PutFileReq.request_id)
  return _s;
}
inline const std::string& PutFileReq::_internal_request_id() const {
  return _impl_.request_id_.Get();
}
inline void PutFileReq::_internal_set_request_id(const std::string& value) {
  
  _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PutFileReq::_internal_mutable_request_id() {
  
  return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PutFileReq::release_request_id() {
  // @@protoc_insertion_point(field_release:messageSystem.PutFileReq.request_id)
  return _impl_.request_id_.Release();
}
inline void PutFileReq::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_id_.IsDefault()) {
    _impl_.request_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.PutFileReq.request_id)
}

// optional string user_id = 2;
inline bool PutFileReq::_internal_has_user_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PutFileReq::has_user_id() const {
  return _internal_has_user_id();
}
inline void PutFileReq::clear_user_id() {
  _impl_.user_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PutFileReq::user_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileReq.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PutFileReq::set_user_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.user_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.PutFileReq.user_id)
}
inline std::string* PutFileReq::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.PutFileReq.user_id)
  return _s;
}
inline const std::string& PutFileReq::_internal_user_id() const {
  return _impl_.user_id_.Get();
}
inline void PutFileReq::_internal_set_user_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.user_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PutFileReq::_internal_mutable_user_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.user_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PutFileReq::release_user_id() {
  // @@protoc_insertion_point(field_release:messageSystem.PutFileReq.user_id)
  if (!_internal_has_user_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.user_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PutFileReq::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.user_id_.SetAllocated(user_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.PutFileReq.user_id)
}

// optional string session_id = 3;
inline bool PutFileReq::_internal_has_session_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PutFileReq::has_session_id() const {
  return _internal_has_session_id();
}
inline void PutFileReq::clear_session_id() {
  _impl_.session_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& PutFileReq::session_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileReq.session_id)
  return _internal_session_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PutFileReq::set_session_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.session_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.PutFileReq.session_id)
}
inline std::string* PutFileReq::mutable_session_id() {
  std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.PutFileReq.session_id)
  return _s;
}
inline const std::string& PutFileReq::_internal_session_id() const {
  return _impl_.session_id_.Get();
}
inline void PutFileReq::_internal_set_session_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.session_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PutFileReq::_internal_mutable_session_id() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.session_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PutFileReq::release_session_id() {
  // @@protoc_insertion_point(field_release:messageSystem.PutFileReq.session_id)
  if (!_internal_has_session_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.session_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PutFileReq::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.session_id_.SetAllocated(session_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.PutFileReq.session_id)
}

// repeated .messageSystem.FileUploadData file_data = 4;
inline int PutFileReq::_internal_file_data_size() const {
  return _impl_.file_data_.size();
}
inline int PutFileReq::file_data_size() const {
  return _internal_file_data_size();
}
inline ::messageSystem::FileUploadData* PutFileReq::mutable_file_data(int index) {
  // @@protoc_insertion_point(field_mutable:messageSystem.PutFileReq.file_data)
  return _impl_.file_data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileUploadData >*
PutFileReq::mutable_file_data() {
  // @@protoc_insertion_point(field_mutable_list:messageSystem.PutFileReq.file_data)
  return &_impl_.file_data_;
}
inline const ::messageSystem::FileUploadData& PutFileReq::_internal_file_data(int index) const {
  return _impl_.file_data_.Get(index);
}
inline const ::messageSystem::FileUploadData& PutFileReq::file_data(int index) const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileReq.file_data)
  return _internal_file_data(index);
}
inline ::messageSystem::FileUploadData* PutFileReq::_internal_add_file_data() {
  return _impl_.file_data_.Add();
}
inline ::messageSystem::FileUploadData* PutFileReq::add_file_data() {
  ::messageSystem::FileUploadData* _add = _internal_add_file_data();
  // @@protoc_insertion_point(field_add:messageSystem.PutFileReq.file_data)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileUploadData >&
PutFileReq::file_data() const {
  // @@protoc_insertion_point(field_list:messageSystem.PutFileReq.file_data)
  return _impl_.file_data_;
}

// -------------------------------------------------------------------

// PutFileRsp

// string request_id = 1;
inline void PutFileRsp::clear_request_id() {
  _impl_.request_id_.ClearToEmpty();
}
inline const std::string& PutFileRsp::request_id() const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileRsp.request_id)
  return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PutFileRsp::set_request_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.PutFileRsp.request_id)
}
inline std::string* PutFileRsp::mutable_request_id() {
  std::string* _s = _internal_mutable_request_id();
  // @@protoc_insertion_point(field_mutable:messageSystem.PutFileRsp.request_id)
  return _s;
}
inline const std::string& PutFileRsp::_internal_request_id() const {
  return _impl_.request_id_.Get();
}
inline void PutFileRsp::_internal_set_request_id(const std::string& value) {
  
  _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PutFileRsp::_internal_mutable_request_id() {
  
  return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PutFileRsp::release_request_id() {
  // @@protoc_insertion_point(field_release:messageSystem.PutFileRsp.request_id)
  return _impl_.request_id_.Release();
}
inline void PutFileRsp::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_id_.IsDefault()) {
    _impl_.request_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.PutFileRsp.request_id)
}

// bool success = 2;
inline void PutFileRsp::clear_success() {
  _impl_.success_ = false;
}
inline bool PutFileRsp::_internal_success() const {
  return _impl_.success_;
}
inline bool PutFileRsp::success() const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileRsp.success)
  return _internal_success();
}
inline void PutFileRsp::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void PutFileRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:messageSystem.PutFileRsp.success)
}

// string errmsg = 3;
inline void PutFileRsp::clear_errmsg() {
  _impl_.errmsg_.ClearToEmpty();
}
inline const std::string& PutFileRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileRsp.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PutFileRsp::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errmsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:messageSystem.PutFileRsp.errmsg)
}
inline std::string* PutFileRsp::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:messageSystem.PutFileRsp.errmsg)
  return _s;
}
inline const std::string& PutFileRsp::_internal_errmsg() const {
  return _impl_.errmsg_.Get();
}
inline void PutFileRsp::_internal_set_errmsg(const std::string& value) {
  
  _impl_.errmsg_.Set(value, GetArenaForAllocation());
}
inline std::string* PutFileRsp::_internal_mutable_errmsg() {
  
  return _impl_.errmsg_.Mutable(GetArenaForAllocation());
}
inline std::string* PutFileRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:messageSystem.PutFileRsp.errmsg)
  return _impl_.errmsg_.Release();
}
inline void PutFileRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  _impl_.errmsg_.SetAllocated(errmsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errmsg_.IsDefault()) {
    _impl_.errmsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:messageSystem.PutFileRsp.errmsg)
}

// repeated .messageSystem.FileMessageInfo file_info = 4;
inline int PutFileRsp::_internal_file_info_size() const {
  return _impl_.file_info_.size();
}
inline int PutFileRsp::file_info_size() const {
  return _internal_file_info_size();
}
inline ::messageSystem::FileMessageInfo* PutFileRsp::mutable_file_info(int index) {
  // @@protoc_insertion_point(field_mutable:messageSystem.PutFileRsp.file_info)
  return _impl_.file_info_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileMessageInfo >*
PutFileRsp::mutable_file_info() {
  // @@protoc_insertion_point(field_mutable_list:messageSystem.PutFileRsp.file_info)
  return &_impl_.file_info_;
}
inline const ::messageSystem::FileMessageInfo& PutFileRsp::_internal_file_info(int index) const {
  return _impl_.file_info_.Get(index);
}
inline const ::messageSystem::FileMessageInfo& PutFileRsp::file_info(int index) const {
  // @@protoc_insertion_point(field_get:messageSystem.PutFileRsp.file_info)
  return _internal_file_info(index);
}
inline ::messageSystem::FileMessageInfo* PutFileRsp::_internal_add_file_info() {
  return _impl_.file_info_.Add();
}
inline ::messageSystem::FileMessageInfo* PutFileRsp::add_file_info() {
  ::messageSystem::FileMessageInfo* _add = _internal_add_file_info();
  // @@protoc_insertion_point(field_add:messageSystem.PutFileRsp.file_info)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::messageSystem::FileMessageInfo >&
PutFileRsp::file_info() const {
  // @@protoc_insertion_point(field_list:messageSystem.PutFileRsp.file_info)
  return _impl_.file_info_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messageSystem

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_file_2eproto
