// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace messageSystem {
PROTOBUF_CONSTEXPR SendMessageReq::SendMessageReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.request_)*/nullptr
  , /*decltype(_impl_.message_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SendMessageReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SendMessageReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SendMessageReqDefaultTypeInternal() {}
  union {
    SendMessageReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SendMessageReqDefaultTypeInternal _SendMessageReq_default_instance_;
PROTOBUF_CONSTEXPR SendMessageRsq::SendMessageRsq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.uids_)*/{}
  , /*decltype(_impl_.response_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SendMessageRsqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SendMessageRsqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SendMessageRsqDefaultTypeInternal() {}
  union {
    SendMessageRsq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SendMessageRsqDefaultTypeInternal _SendMessageRsq_default_instance_;
PROTOBUF_CONSTEXPR RecallMessageReq::RecallMessageReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.request_)*/nullptr
  , /*decltype(_impl_.message_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RecallMessageReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecallMessageReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecallMessageReqDefaultTypeInternal() {}
  union {
    RecallMessageReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecallMessageReqDefaultTypeInternal _RecallMessageReq_default_instance_;
PROTOBUF_CONSTEXPR RecallMessageRsp::RecallMessageRsp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.uids_)*/{}
  , /*decltype(_impl_.response_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RecallMessageRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecallMessageRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecallMessageRspDefaultTypeInternal() {}
  union {
    RecallMessageRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecallMessageRspDefaultTypeInternal _RecallMessageRsp_default_instance_;
PROTOBUF_CONSTEXPR MarkAsReadReq::MarkAsReadReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.coversation_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.request_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MarkAsReadReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MarkAsReadReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MarkAsReadReqDefaultTypeInternal() {}
  union {
    MarkAsReadReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MarkAsReadReqDefaultTypeInternal _MarkAsReadReq_default_instance_;
}  // namespace messageSystem
static ::_pb::Metadata file_level_metadata_message_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_message_2eproto = nullptr;
static const ::_pb::ServiceDescriptor* file_level_service_descriptors_message_2eproto[1];

const uint32_t TableStruct_message_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messageSystem::SendMessageReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messageSystem::SendMessageReq, _impl_.request_),
  PROTOBUF_FIELD_OFFSET(::messageSystem::SendMessageReq, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messageSystem::SendMessageRsq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messageSystem::SendMessageRsq, _impl_.response_),
  PROTOBUF_FIELD_OFFSET(::messageSystem::SendMessageRsq, _impl_.uids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messageSystem::RecallMessageReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messageSystem::RecallMessageReq, _impl_.request_),
  PROTOBUF_FIELD_OFFSET(::messageSystem::RecallMessageReq, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messageSystem::RecallMessageRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messageSystem::RecallMessageRsp, _impl_.response_),
  PROTOBUF_FIELD_OFFSET(::messageSystem::RecallMessageRsp, _impl_.uids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messageSystem::MarkAsReadReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messageSystem::MarkAsReadReq, _impl_.request_),
  PROTOBUF_FIELD_OFFSET(::messageSystem::MarkAsReadReq, _impl_.coversation_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::messageSystem::SendMessageReq)},
  { 8, -1, -1, sizeof(::messageSystem::SendMessageRsq)},
  { 16, -1, -1, sizeof(::messageSystem::RecallMessageReq)},
  { 24, -1, -1, sizeof(::messageSystem::RecallMessageRsp)},
  { 32, -1, -1, sizeof(::messageSystem::MarkAsReadReq)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::messageSystem::_SendMessageReq_default_instance_._instance,
  &::messageSystem::_SendMessageRsq_default_instance_._instance,
  &::messageSystem::_RecallMessageReq_default_instance_._instance,
  &::messageSystem::_RecallMessageRsp_default_instance_._instance,
  &::messageSystem::_MarkAsReadReq_default_instance_._instance,
};

const char descriptor_table_protodef_message_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rmessage.proto\022\rmessageSystem\032\ncomm.pro"
  "to\"f\n\016SendMessageReq\022\'\n\007request\030\001 \001(\0132\026."
  "messageSystem.CommReq\022+\n\007message\030\002 \001(\0132\032"
  ".messageSystem.MessageInfo\"H\n\016SendMessag"
  "eRsq\022(\n\010response\030\001 \001(\0132\026.messageSystem.C"
  "ommRsp\022\014\n\004uids\030\002 \003(\t\"h\n\020RecallMessageReq"
  "\022\'\n\007request\030\001 \001(\0132\026.messageSystem.CommRe"
  "q\022+\n\007message\030\002 \001(\0132\032.messageSystem.Messa"
  "geInfo\"J\n\020RecallMessageRsp\022(\n\010response\030\001"
  " \001(\0132\026.messageSystem.CommRsp\022\014\n\004uids\030\002 \003"
  "(\t\"P\n\rMarkAsReadReq\022\'\n\007request\030\001 \001(\0132\026.m"
  "essageSystem.CommReq\022\026\n\016coversation_id\030\002"
  " \001(\t2\363\001\n\rMessageServer\022K\n\013SendMessage\022\035."
  "messageSystem.SendMessageReq\032\035.messageSy"
  "stem.SendMessageRsq\022Q\n\rRecallMessage\022\037.m"
  "essageSystem.RecallMessageReq\032\037.messageS"
  "ystem.RecallMessageRsp\022B\n\nMarkAsRead\022\034.m"
  "essageSystem.MarkAsReadReq\032\026.messageSyst"
  "em.CommRspB\003\200\001\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_message_2eproto_deps[1] = {
  &::descriptor_table_comm_2eproto,
};
static ::_pbi::once_flag descriptor_table_message_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false, false, 743, descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once, descriptor_table_message_2eproto_deps, 1, 5,
    schemas, file_default_instances, TableStruct_message_2eproto::offsets,
    file_level_metadata_message_2eproto, file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_message_2eproto_getter() {
  return &descriptor_table_message_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_message_2eproto(&descriptor_table_message_2eproto);
namespace messageSystem {

// ===================================================================

class SendMessageReq::_Internal {
 public:
  static const ::messageSystem::CommReq& request(const SendMessageReq* msg);
  static const ::messageSystem::MessageInfo& message(const SendMessageReq* msg);
};

const ::messageSystem::CommReq&
SendMessageReq::_Internal::request(const SendMessageReq* msg) {
  return *msg->_impl_.request_;
}
const ::messageSystem::MessageInfo&
SendMessageReq::_Internal::message(const SendMessageReq* msg) {
  return *msg->_impl_.message_;
}
void SendMessageReq::clear_request() {
  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
}
void SendMessageReq::clear_message() {
  if (GetArenaForAllocation() == nullptr && _impl_.message_ != nullptr) {
    delete _impl_.message_;
  }
  _impl_.message_ = nullptr;
}
SendMessageReq::SendMessageReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messageSystem.SendMessageReq)
}
SendMessageReq::SendMessageReq(const SendMessageReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SendMessageReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_request()) {
    _this->_impl_.request_ = new ::messageSystem::CommReq(*from._impl_.request_);
  }
  if (from._internal_has_message()) {
    _this->_impl_.message_ = new ::messageSystem::MessageInfo(*from._impl_.message_);
  }
  // @@protoc_insertion_point(copy_constructor:messageSystem.SendMessageReq)
}

inline void SendMessageReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SendMessageReq::~SendMessageReq() {
  // @@protoc_insertion_point(destructor:messageSystem.SendMessageReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SendMessageReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.request_;
  if (this != internal_default_instance()) delete _impl_.message_;
}

void SendMessageReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SendMessageReq::Clear() {
// @@protoc_insertion_point(message_clear_start:messageSystem.SendMessageReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.message_ != nullptr) {
    delete _impl_.message_;
  }
  _impl_.message_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendMessageReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .messageSystem.CommReq request = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .messageSystem.MessageInfo message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_message(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SendMessageReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messageSystem.SendMessageReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .messageSystem.CommReq request = 1;
  if (this->_internal_has_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::request(this),
        _Internal::request(this).GetCachedSize(), target, stream);
  }

  // .messageSystem.MessageInfo message = 2;
  if (this->_internal_has_message()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::message(this),
        _Internal::message(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messageSystem.SendMessageReq)
  return target;
}

size_t SendMessageReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messageSystem.SendMessageReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .messageSystem.CommReq request = 1;
  if (this->_internal_has_request()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.request_);
  }

  // .messageSystem.MessageInfo message = 2;
  if (this->_internal_has_message()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendMessageReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SendMessageReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendMessageReq::GetClassData() const { return &_class_data_; }


void SendMessageReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SendMessageReq*>(&to_msg);
  auto& from = static_cast<const SendMessageReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messageSystem.SendMessageReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_request()) {
    _this->_internal_mutable_request()->::messageSystem::CommReq::MergeFrom(
        from._internal_request());
  }
  if (from._internal_has_message()) {
    _this->_internal_mutable_message()->::messageSystem::MessageInfo::MergeFrom(
        from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendMessageReq::CopyFrom(const SendMessageReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messageSystem.SendMessageReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendMessageReq::IsInitialized() const {
  return true;
}

void SendMessageReq::InternalSwap(SendMessageReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SendMessageReq, _impl_.message_)
      + sizeof(SendMessageReq::_impl_.message_)
      - PROTOBUF_FIELD_OFFSET(SendMessageReq, _impl_.request_)>(
          reinterpret_cast<char*>(&_impl_.request_),
          reinterpret_cast<char*>(&other->_impl_.request_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SendMessageReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[0]);
}

// ===================================================================

class SendMessageRsq::_Internal {
 public:
  static const ::messageSystem::CommRsp& response(const SendMessageRsq* msg);
};

const ::messageSystem::CommRsp&
SendMessageRsq::_Internal::response(const SendMessageRsq* msg) {
  return *msg->_impl_.response_;
}
void SendMessageRsq::clear_response() {
  if (GetArenaForAllocation() == nullptr && _impl_.response_ != nullptr) {
    delete _impl_.response_;
  }
  _impl_.response_ = nullptr;
}
SendMessageRsq::SendMessageRsq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messageSystem.SendMessageRsq)
}
SendMessageRsq::SendMessageRsq(const SendMessageRsq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SendMessageRsq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.uids_){from._impl_.uids_}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_response()) {
    _this->_impl_.response_ = new ::messageSystem::CommRsp(*from._impl_.response_);
  }
  // @@protoc_insertion_point(copy_constructor:messageSystem.SendMessageRsq)
}

inline void SendMessageRsq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.uids_){arena}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SendMessageRsq::~SendMessageRsq() {
  // @@protoc_insertion_point(destructor:messageSystem.SendMessageRsq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SendMessageRsq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.uids_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.response_;
}

void SendMessageRsq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SendMessageRsq::Clear() {
// @@protoc_insertion_point(message_clear_start:messageSystem.SendMessageRsq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uids_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.response_ != nullptr) {
    delete _impl_.response_;
  }
  _impl_.response_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendMessageRsq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .messageSystem.CommRsp response = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string uids = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_uids();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "messageSystem.SendMessageRsq.uids"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SendMessageRsq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messageSystem.SendMessageRsq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .messageSystem.CommRsp response = 1;
  if (this->_internal_has_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::response(this),
        _Internal::response(this).GetCachedSize(), target, stream);
  }

  // repeated string uids = 2;
  for (int i = 0, n = this->_internal_uids_size(); i < n; i++) {
    const auto& s = this->_internal_uids(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messageSystem.SendMessageRsq.uids");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messageSystem.SendMessageRsq)
  return target;
}

size_t SendMessageRsq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messageSystem.SendMessageRsq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string uids = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.uids_.size());
  for (int i = 0, n = _impl_.uids_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.uids_.Get(i));
  }

  // .messageSystem.CommRsp response = 1;
  if (this->_internal_has_response()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.response_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendMessageRsq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SendMessageRsq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendMessageRsq::GetClassData() const { return &_class_data_; }


void SendMessageRsq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SendMessageRsq*>(&to_msg);
  auto& from = static_cast<const SendMessageRsq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messageSystem.SendMessageRsq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.uids_.MergeFrom(from._impl_.uids_);
  if (from._internal_has_response()) {
    _this->_internal_mutable_response()->::messageSystem::CommRsp::MergeFrom(
        from._internal_response());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendMessageRsq::CopyFrom(const SendMessageRsq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messageSystem.SendMessageRsq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendMessageRsq::IsInitialized() const {
  return true;
}

void SendMessageRsq::InternalSwap(SendMessageRsq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.uids_.InternalSwap(&other->_impl_.uids_);
  swap(_impl_.response_, other->_impl_.response_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SendMessageRsq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[1]);
}

// ===================================================================

class RecallMessageReq::_Internal {
 public:
  static const ::messageSystem::CommReq& request(const RecallMessageReq* msg);
  static const ::messageSystem::MessageInfo& message(const RecallMessageReq* msg);
};

const ::messageSystem::CommReq&
RecallMessageReq::_Internal::request(const RecallMessageReq* msg) {
  return *msg->_impl_.request_;
}
const ::messageSystem::MessageInfo&
RecallMessageReq::_Internal::message(const RecallMessageReq* msg) {
  return *msg->_impl_.message_;
}
void RecallMessageReq::clear_request() {
  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
}
void RecallMessageReq::clear_message() {
  if (GetArenaForAllocation() == nullptr && _impl_.message_ != nullptr) {
    delete _impl_.message_;
  }
  _impl_.message_ = nullptr;
}
RecallMessageReq::RecallMessageReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messageSystem.RecallMessageReq)
}
RecallMessageReq::RecallMessageReq(const RecallMessageReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RecallMessageReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_request()) {
    _this->_impl_.request_ = new ::messageSystem::CommReq(*from._impl_.request_);
  }
  if (from._internal_has_message()) {
    _this->_impl_.message_ = new ::messageSystem::MessageInfo(*from._impl_.message_);
  }
  // @@protoc_insertion_point(copy_constructor:messageSystem.RecallMessageReq)
}

inline void RecallMessageReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RecallMessageReq::~RecallMessageReq() {
  // @@protoc_insertion_point(destructor:messageSystem.RecallMessageReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RecallMessageReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.request_;
  if (this != internal_default_instance()) delete _impl_.message_;
}

void RecallMessageReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RecallMessageReq::Clear() {
// @@protoc_insertion_point(message_clear_start:messageSystem.RecallMessageReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.message_ != nullptr) {
    delete _impl_.message_;
  }
  _impl_.message_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RecallMessageReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .messageSystem.CommReq request = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .messageSystem.MessageInfo message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_message(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RecallMessageReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messageSystem.RecallMessageReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .messageSystem.CommReq request = 1;
  if (this->_internal_has_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::request(this),
        _Internal::request(this).GetCachedSize(), target, stream);
  }

  // .messageSystem.MessageInfo message = 2;
  if (this->_internal_has_message()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::message(this),
        _Internal::message(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messageSystem.RecallMessageReq)
  return target;
}

size_t RecallMessageReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messageSystem.RecallMessageReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .messageSystem.CommReq request = 1;
  if (this->_internal_has_request()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.request_);
  }

  // .messageSystem.MessageInfo message = 2;
  if (this->_internal_has_message()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RecallMessageReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RecallMessageReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RecallMessageReq::GetClassData() const { return &_class_data_; }


void RecallMessageReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RecallMessageReq*>(&to_msg);
  auto& from = static_cast<const RecallMessageReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messageSystem.RecallMessageReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_request()) {
    _this->_internal_mutable_request()->::messageSystem::CommReq::MergeFrom(
        from._internal_request());
  }
  if (from._internal_has_message()) {
    _this->_internal_mutable_message()->::messageSystem::MessageInfo::MergeFrom(
        from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RecallMessageReq::CopyFrom(const RecallMessageReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messageSystem.RecallMessageReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RecallMessageReq::IsInitialized() const {
  return true;
}

void RecallMessageReq::InternalSwap(RecallMessageReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RecallMessageReq, _impl_.message_)
      + sizeof(RecallMessageReq::_impl_.message_)
      - PROTOBUF_FIELD_OFFSET(RecallMessageReq, _impl_.request_)>(
          reinterpret_cast<char*>(&_impl_.request_),
          reinterpret_cast<char*>(&other->_impl_.request_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RecallMessageReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[2]);
}

// ===================================================================

class RecallMessageRsp::_Internal {
 public:
  static const ::messageSystem::CommRsp& response(const RecallMessageRsp* msg);
};

const ::messageSystem::CommRsp&
RecallMessageRsp::_Internal::response(const RecallMessageRsp* msg) {
  return *msg->_impl_.response_;
}
void RecallMessageRsp::clear_response() {
  if (GetArenaForAllocation() == nullptr && _impl_.response_ != nullptr) {
    delete _impl_.response_;
  }
  _impl_.response_ = nullptr;
}
RecallMessageRsp::RecallMessageRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messageSystem.RecallMessageRsp)
}
RecallMessageRsp::RecallMessageRsp(const RecallMessageRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RecallMessageRsp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.uids_){from._impl_.uids_}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_response()) {
    _this->_impl_.response_ = new ::messageSystem::CommRsp(*from._impl_.response_);
  }
  // @@protoc_insertion_point(copy_constructor:messageSystem.RecallMessageRsp)
}

inline void RecallMessageRsp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.uids_){arena}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RecallMessageRsp::~RecallMessageRsp() {
  // @@protoc_insertion_point(destructor:messageSystem.RecallMessageRsp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RecallMessageRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.uids_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.response_;
}

void RecallMessageRsp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RecallMessageRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:messageSystem.RecallMessageRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uids_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.response_ != nullptr) {
    delete _impl_.response_;
  }
  _impl_.response_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RecallMessageRsp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .messageSystem.CommRsp response = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string uids = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_uids();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "messageSystem.RecallMessageRsp.uids"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RecallMessageRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messageSystem.RecallMessageRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .messageSystem.CommRsp response = 1;
  if (this->_internal_has_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::response(this),
        _Internal::response(this).GetCachedSize(), target, stream);
  }

  // repeated string uids = 2;
  for (int i = 0, n = this->_internal_uids_size(); i < n; i++) {
    const auto& s = this->_internal_uids(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messageSystem.RecallMessageRsp.uids");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messageSystem.RecallMessageRsp)
  return target;
}

size_t RecallMessageRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messageSystem.RecallMessageRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string uids = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.uids_.size());
  for (int i = 0, n = _impl_.uids_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.uids_.Get(i));
  }

  // .messageSystem.CommRsp response = 1;
  if (this->_internal_has_response()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.response_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RecallMessageRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RecallMessageRsp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RecallMessageRsp::GetClassData() const { return &_class_data_; }


void RecallMessageRsp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RecallMessageRsp*>(&to_msg);
  auto& from = static_cast<const RecallMessageRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messageSystem.RecallMessageRsp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.uids_.MergeFrom(from._impl_.uids_);
  if (from._internal_has_response()) {
    _this->_internal_mutable_response()->::messageSystem::CommRsp::MergeFrom(
        from._internal_response());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RecallMessageRsp::CopyFrom(const RecallMessageRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messageSystem.RecallMessageRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RecallMessageRsp::IsInitialized() const {
  return true;
}

void RecallMessageRsp::InternalSwap(RecallMessageRsp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.uids_.InternalSwap(&other->_impl_.uids_);
  swap(_impl_.response_, other->_impl_.response_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RecallMessageRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[3]);
}

// ===================================================================

class MarkAsReadReq::_Internal {
 public:
  static const ::messageSystem::CommReq& request(const MarkAsReadReq* msg);
};

const ::messageSystem::CommReq&
MarkAsReadReq::_Internal::request(const MarkAsReadReq* msg) {
  return *msg->_impl_.request_;
}
void MarkAsReadReq::clear_request() {
  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
}
MarkAsReadReq::MarkAsReadReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messageSystem.MarkAsReadReq)
}
MarkAsReadReq::MarkAsReadReq(const MarkAsReadReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MarkAsReadReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.coversation_id_){}
    , decltype(_impl_.request_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.coversation_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.coversation_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_coversation_id().empty()) {
    _this->_impl_.coversation_id_.Set(from._internal_coversation_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_request()) {
    _this->_impl_.request_ = new ::messageSystem::CommReq(*from._impl_.request_);
  }
  // @@protoc_insertion_point(copy_constructor:messageSystem.MarkAsReadReq)
}

inline void MarkAsReadReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.coversation_id_){}
    , decltype(_impl_.request_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.coversation_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.coversation_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MarkAsReadReq::~MarkAsReadReq() {
  // @@protoc_insertion_point(destructor:messageSystem.MarkAsReadReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MarkAsReadReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.coversation_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.request_;
}

void MarkAsReadReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MarkAsReadReq::Clear() {
// @@protoc_insertion_point(message_clear_start:messageSystem.MarkAsReadReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.coversation_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MarkAsReadReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .messageSystem.CommReq request = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string coversation_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_coversation_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "messageSystem.MarkAsReadReq.coversation_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MarkAsReadReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messageSystem.MarkAsReadReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .messageSystem.CommReq request = 1;
  if (this->_internal_has_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::request(this),
        _Internal::request(this).GetCachedSize(), target, stream);
  }

  // string coversation_id = 2;
  if (!this->_internal_coversation_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_coversation_id().data(), static_cast<int>(this->_internal_coversation_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messageSystem.MarkAsReadReq.coversation_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_coversation_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messageSystem.MarkAsReadReq)
  return target;
}

size_t MarkAsReadReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messageSystem.MarkAsReadReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string coversation_id = 2;
  if (!this->_internal_coversation_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_coversation_id());
  }

  // .messageSystem.CommReq request = 1;
  if (this->_internal_has_request()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.request_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MarkAsReadReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MarkAsReadReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MarkAsReadReq::GetClassData() const { return &_class_data_; }


void MarkAsReadReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MarkAsReadReq*>(&to_msg);
  auto& from = static_cast<const MarkAsReadReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messageSystem.MarkAsReadReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_coversation_id().empty()) {
    _this->_internal_set_coversation_id(from._internal_coversation_id());
  }
  if (from._internal_has_request()) {
    _this->_internal_mutable_request()->::messageSystem::CommReq::MergeFrom(
        from._internal_request());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MarkAsReadReq::CopyFrom(const MarkAsReadReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messageSystem.MarkAsReadReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MarkAsReadReq::IsInitialized() const {
  return true;
}

void MarkAsReadReq::InternalSwap(MarkAsReadReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.coversation_id_, lhs_arena,
      &other->_impl_.coversation_id_, rhs_arena
  );
  swap(_impl_.request_, other->_impl_.request_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MarkAsReadReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[4]);
}

// ===================================================================

MessageServer::~MessageServer() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* MessageServer::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_service_descriptors_message_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* MessageServer::GetDescriptor() {
  return descriptor();
}

void MessageServer::SendMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::messageSystem::SendMessageReq*,
                         ::messageSystem::SendMessageRsq*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method SendMessage() not implemented.");
  done->Run();
}

void MessageServer::RecallMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::messageSystem::RecallMessageReq*,
                         ::messageSystem::RecallMessageRsp*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method RecallMessage() not implemented.");
  done->Run();
}

void MessageServer::MarkAsRead(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::messageSystem::MarkAsReadReq*,
                         ::messageSystem::CommRsp*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method MarkAsRead() not implemented.");
  done->Run();
}

void MessageServer::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_message_2eproto[0]);
  switch(method->index()) {
    case 0:
      SendMessage(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::messageSystem::SendMessageReq*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::messageSystem::SendMessageRsq*>(
                 response),
             done);
      break;
    case 1:
      RecallMessage(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::messageSystem::RecallMessageReq*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::messageSystem::RecallMessageRsp*>(
                 response),
             done);
      break;
    case 2:
      MarkAsRead(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::messageSystem::MarkAsReadReq*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::messageSystem::CommRsp*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& MessageServer::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::messageSystem::SendMessageReq::default_instance();
    case 1:
      return ::messageSystem::RecallMessageReq::default_instance();
    case 2:
      return ::messageSystem::MarkAsReadReq::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& MessageServer::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::messageSystem::SendMessageRsq::default_instance();
    case 1:
      return ::messageSystem::RecallMessageRsp::default_instance();
    case 2:
      return ::messageSystem::CommRsp::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

MessageServer_Stub::MessageServer_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
MessageServer_Stub::MessageServer_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
MessageServer_Stub::~MessageServer_Stub() {
  if (owns_channel_) delete channel_;
}

void MessageServer_Stub::SendMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::messageSystem::SendMessageReq* request,
                              ::messageSystem::SendMessageRsq* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void MessageServer_Stub::RecallMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::messageSystem::RecallMessageReq* request,
                              ::messageSystem::RecallMessageRsp* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void MessageServer_Stub::MarkAsRead(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::messageSystem::MarkAsReadReq* request,
                              ::messageSystem::CommRsp* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace messageSystem
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::messageSystem::SendMessageReq*
Arena::CreateMaybeMessage< ::messageSystem::SendMessageReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messageSystem::SendMessageReq >(arena);
}
template<> PROTOBUF_NOINLINE ::messageSystem::SendMessageRsq*
Arena::CreateMaybeMessage< ::messageSystem::SendMessageRsq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messageSystem::SendMessageRsq >(arena);
}
template<> PROTOBUF_NOINLINE ::messageSystem::RecallMessageReq*
Arena::CreateMaybeMessage< ::messageSystem::RecallMessageReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messageSystem::RecallMessageReq >(arena);
}
template<> PROTOBUF_NOINLINE ::messageSystem::RecallMessageRsp*
Arena::CreateMaybeMessage< ::messageSystem::RecallMessageRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messageSystem::RecallMessageRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::messageSystem::MarkAsReadReq*
Arena::CreateMaybeMessage< ::messageSystem::MarkAsReadReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messageSystem::MarkAsReadReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
