// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "friend-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/view-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/view-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // Friendships
  //

  struct access::object_traits_impl< ::Friendships, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::Friendships, id_mysql >::id_type
  access::object_traits_impl< ::Friendships, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::Friendships, id_mysql >::id_type
  access::object_traits_impl< ::Friendships, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Friendships, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // uid
    //
    t[1UL] = 0;

    // friend_uid
    //
    t[2UL] = 0;

    // status
    //
    if (t[3UL])
    {
      if (mysql::enum_traits::grow (i.status_value, i.status_size))
        grew = true;
      else
        t[3UL] = 0;
    }

    // remark
    //
    if (t[4UL])
    {
      i.remark_value.capacity (i.remark_size);
      grew = true;
    }

    // created_time
    //
    t[5UL] = 0;

    // updated_time
    //
    t[6UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::Friendships, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // uid
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.uid_value;
    b[n].is_null = &i.uid_null;
    n++;

    // friend_uid
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.friend_uid_value;
    b[n].is_null = &i.friend_uid_null;
    n++;

    // status
    //
    mysql::enum_traits::bind (b[n],
                              i.status_value,
                              i.status_size,
                              &i.status_null);
    n++;

    // remark
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.remark_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.remark_value.capacity ());
    b[n].length = &i.remark_size;
    b[n].is_null = &i.remark_null;
    n++;

    // created_time
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.created_time_value;
    b[n].is_null = &i.created_time_null;
    n++;

    // updated_time
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.updated_time_value;
    b[n].is_null = &i.updated_time_null;
    n++;
  }

  void access::object_traits_impl< ::Friendships, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Friendships, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      long unsigned int const& v =
        o.id;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, v);
      i.id_null = is_null;
    }

    // uid
    //
    {
      ::size_t const& v =
        o.uid;

      bool is_null (false);
      mysql::value_traits<
          ::size_t,
          mysql::id_ulonglong >::set_image (
        i.uid_value, is_null, v);
      i.uid_null = is_null;
    }

    // friend_uid
    //
    {
      ::size_t const& v =
        o.friend_uid;

      bool is_null (false);
      mysql::value_traits<
          ::size_t,
          mysql::id_ulonglong >::set_image (
        i.friend_uid_value, is_null, v);
      i.friend_uid_null = is_null;
    }

    // status
    //
    {
      ::FriendShipStatus const& v =
        o.status;

      bool is_null (false);
      if (mysql::enum_traits::set_image (
            i.status_value,
            i.status_size,
            is_null,
            v))
        grew = true;

      i.status_null = is_null;
    }

    // remark
    //
    {
      ::std::string const& v =
        o.remark;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.remark_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.remark_value,
        size,
        is_null,
        v);
      i.remark_null = is_null;
      i.remark_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.remark_value.capacity ());
    }

    // created_time
    //
    {
      long unsigned int const& v =
        o.created_time;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.created_time_value, is_null, v);
      i.created_time_null = is_null;
    }

    // updated_time
    //
    {
      long unsigned int const& v =
        o.updated_time;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.updated_time_value, is_null, v);
      i.updated_time_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::Friendships, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      long unsigned int& v =
        o.id;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // uid
    //
    {
      ::size_t& v =
        o.uid;

      mysql::value_traits<
          ::size_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.uid_value,
        i.uid_null);
    }

    // friend_uid
    //
    {
      ::size_t& v =
        o.friend_uid;

      mysql::value_traits<
          ::size_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.friend_uid_value,
        i.friend_uid_null);
    }

    // status
    //
    {
      ::FriendShipStatus& v =
        o.status;

      mysql::enum_traits::set_value (
        v,
        i.status_value,
        i.status_size,
        i.status_null);
    }

    // remark
    //
    {
      ::std::string& v =
        o.remark;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.remark_value,
        i.remark_size,
        i.remark_null);
    }

    // created_time
    //
    {
      long unsigned int& v =
        o.created_time;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.created_time_value,
        i.created_time_null);
    }

    // updated_time
    //
    {
      long unsigned int& v =
        o.updated_time;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.updated_time_value,
        i.updated_time_null);
    }
  }

  void access::object_traits_impl< ::Friendships, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::Friendships, id_mysql >::persist_statement[] =
  "INSERT INTO `friendships` "
  "(`id`, "
  "`uid`, "
  "`friend_uid`, "
  "`status`, "
  "`remark`, "
  "`created_time`, "
  "`updated_time`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Friendships, id_mysql >::find_statement[] =
  "SELECT "
  "`friendships`.`id`, "
  "`friendships`.`uid`, "
  "`friendships`.`friend_uid`, "
  "CONCAT(`friendships`.`status`+0,' ',`friendships`.`status`), "
  "`friendships`.`remark`, "
  "`friendships`.`created_time`, "
  "`friendships`.`updated_time` "
  "FROM `friendships` "
  "WHERE `friendships`.`id`=?";

  const char access::object_traits_impl< ::Friendships, id_mysql >::update_statement[] =
  "UPDATE `friendships` "
  "SET "
  "`uid`=?, "
  "`friend_uid`=?, "
  "`status`=?, "
  "`remark`=?, "
  "`created_time`=?, "
  "`updated_time`=? "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::Friendships, id_mysql >::erase_statement[] =
  "DELETE FROM `friendships` "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::Friendships, id_mysql >::query_statement[] =
  "SELECT "
  "`friendships`.`id`, "
  "`friendships`.`uid`, "
  "`friendships`.`friend_uid`, "
  "CONCAT(`friendships`.`status`+0,' ',`friendships`.`status`), "
  "`friendships`.`remark`, "
  "`friendships`.`created_time`, "
  "`friendships`.`updated_time` "
  "FROM `friendships`";

  const char access::object_traits_impl< ::Friendships, id_mysql >::erase_query_statement[] =
  "DELETE FROM `friendships`";

  const char access::object_traits_impl< ::Friendships, id_mysql >::table_name[] =
  "`friendships`";

  void access::object_traits_impl< ::Friendships, id_mysql >::
  persist (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Friendships, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Friendships, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Friendships, id_mysql >::pointer_type
  access::object_traits_impl< ::Friendships, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Friendships, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Friendships, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Friendships, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Friendships, id_mysql >::object_type >
  access::object_traits_impl< ::Friendships, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Friendships, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // FindFriend
  //

  bool access::view_traits_impl< ::FindFriend, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // friend_id
    //
    t[0UL] = 0;

    // friend_name
    //
    if (t[1UL])
    {
      i.friend_name_value.capacity (i.friend_name_size);
      grew = true;
    }

    // remark
    //
    if (t[2UL])
    {
      i.remark_value.capacity (i.remark_size);
      grew = true;
    }

    // age
    //
    t[3UL] = 0;

    // email
    //
    if (t[4UL])
    {
      i.email_value.capacity (i.email_size);
      grew = true;
    }

    // desc
    //
    if (t[5UL])
    {
      i.desc_value.capacity (i.desc_size);
      grew = true;
    }

    // avatar
    //
    if (t[6UL])
    {
      i.avatar_value.capacity (i.avatar_size);
      grew = true;
    }

    // sex
    //
    if (t[7UL])
    {
      if (mysql::enum_traits::grow (i.sex_value, i.sex_size))
        grew = true;
      else
        t[7UL] = 0;
    }

    // created_time
    //
    t[8UL] = 0;

    // updated_time
    //
    t[9UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::FindFriend, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i)
  {
    using namespace mysql;

    mysql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // friend_id
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.friend_id_value;
    b[n].is_null = &i.friend_id_null;
    n++;

    // friend_name
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.friend_name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.friend_name_value.capacity ());
    b[n].length = &i.friend_name_size;
    b[n].is_null = &i.friend_name_null;
    n++;

    // remark
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.remark_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.remark_value.capacity ());
    b[n].length = &i.remark_size;
    b[n].is_null = &i.remark_null;
    n++;

    // age
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.age_value;
    b[n].is_null = &i.age_null;
    n++;

    // email
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.email_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.email_value.capacity ());
    b[n].length = &i.email_size;
    b[n].is_null = &i.email_null;
    n++;

    // desc
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.desc_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.desc_value.capacity ());
    b[n].length = &i.desc_size;
    b[n].is_null = &i.desc_null;
    n++;

    // avatar
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.avatar_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.avatar_value.capacity ());
    b[n].length = &i.avatar_size;
    b[n].is_null = &i.avatar_null;
    n++;

    // sex
    //
    mysql::enum_traits::bind (b[n],
                              i.sex_value,
                              i.sex_size,
                              &i.sex_null);
    n++;

    // created_time
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.created_time_value;
    b[n].is_null = &i.created_time_null;
    n++;

    // updated_time
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.updated_time_value;
    b[n].is_null = &i.updated_time_null;
    n++;
  }

  void access::view_traits_impl< ::FindFriend, id_mysql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // friend_id
    //
    {
      ::size_t& v =
        o.friend_id;

      mysql::value_traits<
          ::size_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.friend_id_value,
        i.friend_id_null);
    }

    // friend_name
    //
    {
      ::std::string& v =
        o.friend_name;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.friend_name_value,
        i.friend_name_size,
        i.friend_name_null);
    }

    // remark
    //
    {
      ::std::string& v =
        o.remark;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.remark_value,
        i.remark_size,
        i.remark_null);
    }

    // age
    //
    {
      int& v =
        o.age;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i.age_value,
        i.age_null);
    }

    // email
    //
    {
      ::std::string& v =
        o.email;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.email_value,
        i.email_size,
        i.email_null);
    }

    // desc
    //
    {
      ::std::string& v =
        o.desc;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.desc_value,
        i.desc_size,
        i.desc_null);
    }

    // avatar
    //
    {
      ::std::string& v =
        o.avatar;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.avatar_value,
        i.avatar_size,
        i.avatar_null);
    }

    // sex
    //
    {
      ::Sex& v =
        o.sex;

      mysql::enum_traits::set_value (
        v,
        i.sex_value,
        i.sex_size,
        i.sex_null);
    }

    // created_time
    //
    {
      long unsigned int& v =
        o.created_time;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.created_time_value,
        i.created_time_null);
    }

    // updated_time
    //
    {
      long unsigned int& v =
        o.updated_time;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.updated_time_value,
        i.updated_time_null);
    }
  }

  access::view_traits_impl< ::FindFriend, id_mysql >::query_base_type
  access::view_traits_impl< ::FindFriend, id_mysql >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "`friendships`.`friend_uid`, "
      "`user`.`name`, "
      "`friendships`.`remark`, "
      "`user`.`age`, "
      "`user`.`email`, "
      "`user`.`desc`, "
      "`user`.`avatar`, "
      "CONCAT(`user`.`sex`+0,' ',`user`.`sex`), "
      "`friendships`.`created_time`, "
      "`friendships`.`updated_time` ");

    r += "FROM `friendships`";

    r += " LEFT JOIN `user` ON";
    // From friend.hxx:31:17
    r += query_columns::User::uid == query_columns::Friendships::friend_uid;

    query_base_type c (
      // From friend.hxx:32:17
      (q.empty () ? query_base_type::true_expr : q));

    c.optimize ();

    if (!c.empty ())
    {
      r += " ";
      r += c.clause_prefix ();
      r += c;
    }

    return r;
  }

  result< access::view_traits_impl< ::FindFriend, id_mysql >::view_type >
  access::view_traits_impl< ::FindFriend, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        qs.clause (),
        false,
        true,
        qs.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) mysql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }
}

#include <odb/post.hxx>
