// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef MESSAGE_OUTBOX_ODB_HXX
#define MESSAGE_OUTBOX_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "message_outbox.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // MessageOutbox
  //
  template <>
  struct class_traits< ::MessageOutbox >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::MessageOutbox >
  {
    public:
    typedef ::MessageOutbox object_type;
    typedef ::MessageOutbox* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // MessageOutbox
  //
  template <typename A>
  struct query_columns< ::MessageOutbox, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // task_type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_type_type_;

    static const task_type_type_ task_type;

    // conversation_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    conversation_id_type_;

    static const conversation_id_type_ conversation_id;

    // msg_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    msg_id_type_;

    static const msg_id_type_ msg_id;

    // payload
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    payload_type_;

    static const payload_type_ payload;

    // status
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    status_type_;

    static const status_type_ status;

    // retry_count
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    retry_count_type_;

    static const retry_count_type_ retry_count;

    // max_retries
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    max_retries_type_;

    static const max_retries_type_ max_retries;

    // next_retry_at
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    next_retry_at_type_;

    static const next_retry_at_type_ next_retry_at;

    // created_at
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    updated_at_type_;

    static const updated_at_type_ updated_at;

    // last_error
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    last_error_type_;

    static const last_error_type_ last_error;
  };

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::id_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::task_type_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  task_type (A::table_name, "`task_type`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::conversation_id_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  conversation_id (A::table_name, "`conversation_id`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::msg_id_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  msg_id (A::table_name, "`msg_id`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::payload_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  payload (A::table_name, "`payload`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::status_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  status (A::table_name, "`status`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::retry_count_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  retry_count (A::table_name, "`retry_count`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::max_retries_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  max_retries (A::table_name, "`max_retries`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::next_retry_at_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  next_retry_at (A::table_name, "`next_retry_at`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::created_at_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  created_at (A::table_name, "`created_at`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::updated_at_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  updated_at (A::table_name, "`updated_at`", 0);

  template <typename A>
  const typename query_columns< ::MessageOutbox, id_mysql, A >::last_error_type_
  query_columns< ::MessageOutbox, id_mysql, A >::
  last_error (A::table_name, "`last_error`", 0);

  template <typename A>
  struct pointer_query_columns< ::MessageOutbox, id_mysql, A >:
    query_columns< ::MessageOutbox, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::MessageOutbox, id_mysql >:
    public access::object_traits< ::MessageOutbox >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      unsigned long long id_value;
      my_bool id_null;

      // task_type
      //
      details::buffer task_type_value;
      unsigned long task_type_size;
      my_bool task_type_null;

      // conversation_id
      //
      details::buffer conversation_id_value;
      unsigned long conversation_id_size;
      my_bool conversation_id_null;

      // msg_id
      //
      unsigned long long msg_id_value;
      my_bool msg_id_null;

      // payload
      //
      details::buffer payload_value;
      unsigned long payload_size;
      my_bool payload_null;

      // status
      //
      int status_value;
      my_bool status_null;

      // retry_count
      //
      int retry_count_value;
      my_bool retry_count_null;

      // max_retries
      //
      int max_retries_value;
      my_bool max_retries_null;

      // next_retry_at
      //
      unsigned long long next_retry_at_value;
      my_bool next_retry_at_null;

      // created_at
      //
      unsigned long long created_at_value;
      my_bool created_at_null;

      // updated_at
      //
      unsigned long long updated_at_value;
      my_bool updated_at_null;

      // last_error
      //
      details::buffer last_error_value;
      unsigned long last_error_size;
      my_bool last_error_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 12UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::MessageOutbox, id_common >:
    public access::object_traits_impl< ::MessageOutbox, id_mysql >
  {
  };

  // MessageOutbox
  //
}

#include "message_outbox-odb.ixx"

#include <odb/post.hxx>

#endif // MESSAGE_OUTBOX_ODB_HXX
