// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef MESSAGE_ODB_HXX
#define MESSAGE_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "message.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Message
  //
  template <>
  struct class_traits< ::Message >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Message >
  {
    public:
    typedef ::Message object_type;
    typedef ::Message* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long long unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Message
  //
  template <typename A>
  struct query_columns< ::Message, id_mysql, A >
  {
    // message_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    message_id_type_;

    static const message_id_type_ message_id;

    // seq
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    seq_type_;

    static const seq_type_ seq;

    // conversation_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    conversation_id_type_;

    static const conversation_id_type_ conversation_id;

    // sender_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    sender_id_type_;

    static const sender_id_type_ sender_id;

    // message_type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    message_type_type_;

    static const message_type_type_ message_type;

    // create_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    create_time_type_;

    static const create_time_type_ create_time;

    // text
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    text_type_;

    static const text_type_ text;

    // file_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    file_id_type_;

    static const file_id_type_ file_id;

    // file_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    file_name_type_;

    static const file_name_type_ file_name;

    // file_size
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    file_size_type_;

    static const file_size_type_ file_size;
  };

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::message_id_type_
  query_columns< ::Message, id_mysql, A >::
  message_id (A::table_name, "`message_id`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::seq_type_
  query_columns< ::Message, id_mysql, A >::
  seq (A::table_name, "`seq`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::conversation_id_type_
  query_columns< ::Message, id_mysql, A >::
  conversation_id (A::table_name, "`conversation_id`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::sender_id_type_
  query_columns< ::Message, id_mysql, A >::
  sender_id (A::table_name, "`sender_id`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::message_type_type_
  query_columns< ::Message, id_mysql, A >::
  message_type (A::table_name, "`message_type`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::create_time_type_
  query_columns< ::Message, id_mysql, A >::
  create_time (A::table_name, "`create_time`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::text_type_
  query_columns< ::Message, id_mysql, A >::
  text (A::table_name, "`text`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::file_id_type_
  query_columns< ::Message, id_mysql, A >::
  file_id (A::table_name, "`file_id`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::file_name_type_
  query_columns< ::Message, id_mysql, A >::
  file_name (A::table_name, "`file_name`", 0);

  template <typename A>
  const typename query_columns< ::Message, id_mysql, A >::file_size_type_
  query_columns< ::Message, id_mysql, A >::
  file_size (A::table_name, "`file_size`", 0);

  template <typename A>
  struct pointer_query_columns< ::Message, id_mysql, A >:
    query_columns< ::Message, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Message, id_mysql >:
    public access::object_traits< ::Message >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // message_id
      //
      unsigned long long message_id_value;
      my_bool message_id_null;

      // seq
      //
      unsigned long long seq_value;
      my_bool seq_null;

      // conversation_id
      //
      details::buffer conversation_id_value;
      unsigned long conversation_id_size;
      my_bool conversation_id_null;

      // sender_id
      //
      details::buffer sender_id_value;
      unsigned long sender_id_size;
      my_bool sender_id_null;

      // message_type
      //
      int message_type_value;
      my_bool message_type_null;

      // create_time
      //
      unsigned long long create_time_value;
      my_bool create_time_null;

      // text
      //
      details::buffer text_value;
      unsigned long text_size;
      my_bool text_null;

      // file_id
      //
      details::buffer file_id_value;
      unsigned long file_id_size;
      my_bool file_id_null;

      // file_name
      //
      details::buffer file_name_value;
      unsigned long file_name_size;
      my_bool file_name_null;

      // file_size
      //
      unsigned int file_size_value;
      my_bool file_size_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Message, id_common >:
    public access::object_traits_impl< ::Message, id_mysql >
  {
  };

  // Message
  //
}

#include "message-odb.ixx"

#include <odb/post.hxx>

#endif // MESSAGE_ODB_HXX
