// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef CONVERSTAION_ODB_HXX
#define CONVERSTAION_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "converstaion.hxx"

#include "../user/user-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Converstaion
  //
  template <>
  struct class_traits< ::Converstaion >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Converstaion >
  {
    public:
    typedef ::Converstaion object_type;
    typedef ::Converstaion* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::size_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // ConverstaionMember
  //
  template <>
  struct class_traits< ::ConverstaionMember >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::ConverstaionMember >
  {
    public:
    typedef ::ConverstaionMember object_type;
    typedef ::ConverstaionMember* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::size_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // PrivateConversation
  //
  template <>
  struct class_traits< ::PrivateConversation >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::PrivateConversation >
  {
    public:
    typedef ::PrivateConversation view_type;
    typedef ::PrivateConversation* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Converstaion
  //
  template <typename A>
  struct query_columns< ::Converstaion, id_mysql, A >
  {
    // conversation_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::size_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    conversation_id_type_;

    static const conversation_id_type_ conversation_id;

    // name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    name_type_;

    static const name_type_ name;

    // type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::ConverstaionType,
        mysql::id_enum >::query_type,
      mysql::id_enum >
    type_type_;

    static const type_type_ type;

    // avatar
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    avatar_type_;

    static const avatar_type_ avatar;

    // created_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    created_time_type_;

    static const created_time_type_ created_time;

    // last_message_content
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    last_message_content_type_;

    static const last_message_content_type_ last_message_content;

    // last_message_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    last_message_time_type_;

    static const last_message_time_type_ last_message_time;
  };

  template <typename A>
  const typename query_columns< ::Converstaion, id_mysql, A >::conversation_id_type_
  query_columns< ::Converstaion, id_mysql, A >::
  conversation_id (A::table_name, "`conversation_id`", 0);

  template <typename A>
  const typename query_columns< ::Converstaion, id_mysql, A >::name_type_
  query_columns< ::Converstaion, id_mysql, A >::
  name (A::table_name, "`name`", 0);

  template <typename A>
  const typename query_columns< ::Converstaion, id_mysql, A >::type_type_
  query_columns< ::Converstaion, id_mysql, A >::
  type (A::table_name, "`type`", 0);

  template <typename A>
  const typename query_columns< ::Converstaion, id_mysql, A >::avatar_type_
  query_columns< ::Converstaion, id_mysql, A >::
  avatar (A::table_name, "`avatar`", 0);

  template <typename A>
  const typename query_columns< ::Converstaion, id_mysql, A >::created_time_type_
  query_columns< ::Converstaion, id_mysql, A >::
  created_time (A::table_name, "`created_time`", 0);

  template <typename A>
  const typename query_columns< ::Converstaion, id_mysql, A >::last_message_content_type_
  query_columns< ::Converstaion, id_mysql, A >::
  last_message_content (A::table_name, "`last_message_content`", 0);

  template <typename A>
  const typename query_columns< ::Converstaion, id_mysql, A >::last_message_time_type_
  query_columns< ::Converstaion, id_mysql, A >::
  last_message_time (A::table_name, "`last_message_time`", 0);

  template <typename A>
  struct pointer_query_columns< ::Converstaion, id_mysql, A >:
    query_columns< ::Converstaion, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Converstaion, id_mysql >:
    public access::object_traits< ::Converstaion >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // conversation_id
      //
      unsigned long long conversation_id_value;
      my_bool conversation_id_null;

      // name
      //
      details::buffer name_value;
      unsigned long name_size;
      my_bool name_null;

      // type
      //
      mysql::value_traits< ::ConverstaionType, mysql::id_enum >::image_type type_value;
      unsigned long type_size;
      my_bool type_null;

      // avatar
      //
      details::buffer avatar_value;
      unsigned long avatar_size;
      my_bool avatar_null;

      // created_time
      //
      unsigned long long created_time_value;
      my_bool created_time_null;

      // last_message_content
      //
      details::buffer last_message_content_value;
      unsigned long last_message_content_size;
      my_bool last_message_content_null;

      // last_message_time
      //
      details::buffer last_message_time_value;
      unsigned long last_message_time_size;
      my_bool last_message_time_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Converstaion, id_common >:
    public access::object_traits_impl< ::Converstaion, id_mysql >
  {
  };

  // ConverstaionMember
  //
  template <typename A>
  struct query_columns< ::ConverstaionMember, id_mysql, A >
  {
    // conversation_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::size_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    conversation_id_type_;

    static const conversation_id_type_ conversation_id;

    // power
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::ConverstaionMemberPower,
        mysql::id_enum >::query_type,
      mysql::id_enum >
    power_type_;

    static const power_type_ power;

    // uid
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::size_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    uid_type_;

    static const uid_type_ uid;

    // conversation_member_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    conversation_member_name_type_;

    static const conversation_member_name_type_ conversation_member_name;

    // conversation_remark_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    conversation_remark_name_type_;

    static const conversation_remark_name_type_ conversation_remark_name;
  };

  template <typename A>
  const typename query_columns< ::ConverstaionMember, id_mysql, A >::conversation_id_type_
  query_columns< ::ConverstaionMember, id_mysql, A >::
  conversation_id (A::table_name, "`conversation_id`", 0);

  template <typename A>
  const typename query_columns< ::ConverstaionMember, id_mysql, A >::power_type_
  query_columns< ::ConverstaionMember, id_mysql, A >::
  power (A::table_name, "`power`", 0);

  template <typename A>
  const typename query_columns< ::ConverstaionMember, id_mysql, A >::uid_type_
  query_columns< ::ConverstaionMember, id_mysql, A >::
  uid (A::table_name, "`uid`", 0);

  template <typename A>
  const typename query_columns< ::ConverstaionMember, id_mysql, A >::conversation_member_name_type_
  query_columns< ::ConverstaionMember, id_mysql, A >::
  conversation_member_name (A::table_name, "`conversation_member_name`", 0);

  template <typename A>
  const typename query_columns< ::ConverstaionMember, id_mysql, A >::conversation_remark_name_type_
  query_columns< ::ConverstaionMember, id_mysql, A >::
  conversation_remark_name (A::table_name, "`conversation_remark_name`", 0);

  template <typename A>
  struct pointer_query_columns< ::ConverstaionMember, id_mysql, A >:
    query_columns< ::ConverstaionMember, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::ConverstaionMember, id_mysql >:
    public access::object_traits< ::ConverstaionMember >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // conversation_id
      //
      unsigned long long conversation_id_value;
      my_bool conversation_id_null;

      // power
      //
      mysql::value_traits< ::ConverstaionMemberPower, mysql::id_enum >::image_type power_value;
      unsigned long power_size;
      my_bool power_null;

      // uid
      //
      unsigned long long uid_value;
      my_bool uid_null;

      // conversation_member_name
      //
      details::buffer conversation_member_name_value;
      unsigned long conversation_member_name_size;
      my_bool conversation_member_name_null;

      // conversation_remark_name
      //
      details::buffer conversation_remark_name_value;
      unsigned long conversation_remark_name_size;
      my_bool conversation_remark_name_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::ConverstaionMember, id_common >:
    public access::object_traits_impl< ::ConverstaionMember, id_mysql >
  {
  };

  // PrivateConversation
  //
  template <>
  class access::view_traits_impl< ::PrivateConversation, id_mysql >:
    public access::view_traits< ::PrivateConversation >
  {
    public:
    struct image_type
    {
      // conversation_id
      //
      unsigned long long conversation_id_value;
      my_bool conversation_id_null;

      // name
      //
      details::buffer name_value;
      unsigned long name_size;
      my_bool name_null;

      // avatar
      //
      details::buffer avatar_value;
      unsigned long avatar_size;
      my_bool avatar_null;

      // created_time
      //
      unsigned long long created_time_value;
      my_bool created_time_null;

      // last_message_content
      //
      details::buffer last_message_content_value;
      unsigned long last_message_content_size;
      my_bool last_message_content_null;

      // last_message_time
      //
      details::buffer last_message_time_value;
      unsigned long last_message_time_size;
      my_bool last_message_time_null;

      std::size_t version;
    };

    typedef mysql::view_statements<view_type> statements_type;

    typedef mysql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 6UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::PrivateConversation, id_common >:
    public access::view_traits_impl< ::PrivateConversation, id_mysql >
  {
  };

  // Converstaion
  //
  // ConverstaionMember
  //
  // PrivateConversation
  //
  struct access::view_traits_impl< ::PrivateConversation, id_mysql >::query_columns
  {
    // Converstaion
    //
    typedef
    odb::pointer_query_columns<
      ::Converstaion,
      id_mysql,
      odb::access::object_traits_impl< ::Converstaion, id_mysql > >
    Converstaion;

    // ConverstaionMember
    //
    typedef
    odb::pointer_query_columns<
      ::ConverstaionMember,
      id_mysql,
      odb::access::object_traits_impl< ::ConverstaionMember, id_mysql > >
    ConverstaionMember;

    // User
    //
    typedef
    odb::pointer_query_columns<
      ::User,
      id_mysql,
      odb::access::object_traits_impl< ::User, id_mysql > >
    User;
  };
}

#include "converstaion-odb.ixx"

#include <odb/post.hxx>

#endif // CONVERSTAION_ODB_HXX
