/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Conversation_member`;

DROP TABLE IF EXISTS `Conversation`;

CREATE TABLE `Conversation` (
  `conversation_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  `type` ENUM('PRIVATE', 'GROUP') NOT NULL,
  `avatar` TEXT NOT NULL,
  `members` BIGINT UNSIGNED NOT NULL,
  `created_time` BIGINT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Conversation_member` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `conversation_id` BIGINT UNSIGNED NOT NULL,
  `power` ENUM('COMMON', 'ADMIN', 'OWNER') NOT NULL,
  `uid` BIGINT UNSIGNED NOT NULL,
  `conversation_member_name` TEXT NOT NULL,
  `conversation_remark_name` TEXT NOT NULL)
 ENGINE=InnoDB;

