/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `converstaion_member`;

DROP TABLE IF EXISTS `converstaion`;

CREATE TABLE `converstaion` (
  `conversation_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  `type` ENUM('PRIVATE', 'GROUP') NOT NULL,
  `avatar` TEXT NOT NULL,
  `created_time` BIGINT UNSIGNED NOT NULL,
  `last_message_content` TEXT NOT NULL,
  `last_message_time` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `converstaion_member` (
  `conversation_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `power` ENUM('COMMON', 'ADMIN', 'OWNER') NOT NULL,
  `uid` BIGINT UNSIGNED NOT NULL,
  `conversation_member_name` TEXT NOT NULL,
  `conversation_remark_name` TEXT NOT NULL)
 ENGINE=InnoDB;

